// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlblqryvyavvveawduct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYmxxcnl2eWF2dnZlYXdkdWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDE4NjIsImV4cCI6MjA2NTU3Nzg2Mn0.aD5yE9QsfT9QJJGMsyKq_P3iaPK8ZNFQbQ-dbBJnXJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});